Administrativo/Models/Editoriais.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Editoriais
    {
        public Editoriais()
        {
            this.Categorias = new HashSet<Categorias>();
            this.Editoriais_Equipe = new HashSet<Editoriais_Equipe>();
            this.Programacao = new HashSet<Programacao>();
            this.Galeria = new HashSet<Galeria>();
            this.Noticias = new HashSet<Noticias>();
            this.Especiais_Secoes = new HashSet<Especiais_Secoes>();
            this.Times = new HashSet<Times>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public bool especial { get; set; }
        public Nullable<int> modeloEspecial { get; set; }
        public bool ativo { get; set; }
        public bool excluido { get; set; }
        public string chave { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public bool esportes { get; set; }
        public string Action { get; set; }
        public bool canal { get; set; }
        public string Descricao { get; set; }
        public string FotoCapa { get; set; }
    
        public virtual ICollection<Categorias> Categorias { get; set; }
        public virtual ICollection<Editoriais_Equipe> Editoriais_Equipe { get; set; }
        public virtual ICollection<Programacao> Programacao { get; set; }
        public virtual ICollection<Galeria> Galeria { get; set; }
        public virtual ICollection<Noticias> Noticias { get; set; }
        public virtual Especiais_Modelos Especiais_Modelos { get; set; }
        public virtual ICollection<Especiais_Secoes> Especiais_Secoes { get; set; }
        public virtual ICollection<Times> Times { get; set; }
    }
}

Administrativo/Controllers/EditoriaisController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using PagedList;
using System.Web.Mvc;
using Administrativo.Models;
using Administrativo.Commons;
using Administrativo.Helpers;
using WebMatrix.WebData;
using Administrativo.Enums;
using Administrativo.ViewModel;
using System.IO;

namespace Administrativo.Controllers
{
    [CustomAuthorize(Roles = "Administrador,Editorias")]
    public class EditoriaisController : BaseController
    {
        public int areaADM = 8;
        protected const string pathOriginal = "~/Conteudo/editoriais/{0}/";

        //
        //
        // GET: /Editoriais/

        public ActionResult Index(int? page, string search = "", string sortField = "", string order = "", string especial = "")
        {

            ViewBag.EditoriaisActive = "active";
            ViewBag.EditoriaisSubActive = "active";
            ViewBag.Search = search;
            ViewBag.Order = order;
            ViewBag.SortField = sortField;
            ViewBag.Page = page;
            allClassOffSort();

            return View(GetListItens(page, search, sortField, order, especial));

        }


        public void allClassOffSort()
        {

            ViewBag.SortClassid = "sorting";
            ViewBag.SortClassnome = "sorting";
            ViewBag.SortClassDataCadastro = "sorting";

        }

        public IPagedList<Editoriais> GetListItens(int? page, string searchParam = "", string sortField = "", string order = "", string especial = "")
        {
            var list = db.Editoriais.Where(x => !x.excluido && !x.esportes);

            var pagedList = from obj in list select obj;
            int pageNumber = (page ?? 1);

            if (!string.IsNullOrEmpty(especial))
            {
                bool opcao = Convert.ToBoolean(Convert.ToInt32(especial));               
                pagedList = pagedList.Where(x => x.especial == opcao);
            }

            if (!string.IsNullOrEmpty(searchParam))
            {
                int outDate = 0;
                int id = int.TryParse(searchParam, out outDate) ? int.Parse(searchParam) : 0;

                pagedList = pagedList.Where(e => e.id == id || e.nome.ToLower().Contains(searchParam.ToLower()));

            }


            switch (sortField)
            {
                case "id":
                    if (order == "ASC")
                    {
                        pagedList = pagedList.OrderBy(e => e.id);
                        ViewBag.SortClassid = "sorting_asc";

                    }
                    else
                    {
                        pagedList = pagedList.OrderByDescending(e => e.id);
                        ViewBag.SortClassid = "sorting_desc";
                    }
                    break;
                case "nome":
                    if (order == "ASC")
                    {
                        pagedList = pagedList.OrderBy(e => e.nome);
                        ViewBag.SortClassnome = "sorting_asc";

                    }
                    else
                    {
                        pagedList = pagedList.OrderByDescending(e => e.nome);
                        ViewBag.SortClassnome = "sorting_desc";
                    }
                    break;
                case "DataCadastro":
                    if (order == "ASC")
                    {
                        pagedList = pagedList.OrderBy(e => e.DataCadastro);
                        ViewBag.SortClassDataCadastro = "sorting_asc";

                    }
                    else
                    {
                        pagedList = pagedList.OrderByDescending(e => e.DataCadastro);
                        ViewBag.SortClassDataCadastro = "sorting_desc";
                    }
                    break;
                default:
                    pagedList = pagedList.OrderByDescending(e => e.id);
                    ViewBag.SortClassid = "sorting_asc";
                    break;
            }

            return pagedList.ToPagedList<Editoriais>(pageNumber, 10);
        }

        //
        // GET: /Editoriais/Details/5

        public ActionResult Details(int id = 0)
        {
            Editoriais editoriais = db.Editoriais.Include("Categorias").FirstOrDefault(a => a.id == id);
            if (editoriais == null)
            {
                return HttpNotFound();
            }
            return View(editoriais);
        }

        //
        // GET: /Editoriais/Create

        public ActionResult Create()
        {
            ViewBag.CategoriasId = new MultiSelectList(db.Categorias.Where(a => !a.Excluido), "Id", "Titulo");
            ViewBag.ModelosEspeciaisId = new SelectList(db.Especiais_Modelos.Where(e => e.especial), "Id", "Tipo");

            return View();
        }

        //
        // POST: /Editoriais/Create

        [HttpPost]
        public ActionResult Create(Editoriais editoriais, HttpPostedFileBase foto, int[] CategoriasId)
        {
            if (ModelState.IsValid)
            {
                editoriais.DataCadastro = DateTime.Now;

                int suffix = 0;

                do
                {
                    editoriais.chave = editoriais.nome.GenerateSlug() + (suffix > 0 ? (suffix++).ToString() : "");
                    suffix++;
                } while (db.Editoriais.Where(o => o.chave == editoriais.chave).Count() > 0);

                db.Editoriais.Add(editoriais);

                if (db.SaveChanges() > 0)
                {
                    #region uploads

                    if (foto != null)
                    {
                        var fileOriginal = Server.MapPath(string.Format(pathOriginal, editoriais.id));
                        var path365x240 = Server.MapPath(string.Format(pathOriginal + "365x240/", editoriais.id));

                        editoriais.FotoCapa = Utils.SaveFileBase(fileOriginal, foto);

                        Utils.resizeImageAndSave3(Path.Combine(fileOriginal, editoriais.FotoCapa), 365, 240, path365x240);
                    }


                    db.Entry(editoriais).State = EntityState.Modified;
                    #endregion
                }

                db.SaveChanges();
                GerenciaLogs.saveLog(ref db, WebSecurity.GetUserId(User.Identity.Name), areaADM, TipoAcesso.Insercao, editoriais.id);
                return RedirectToAction("Index");
            }
            ViewBag.ModelosEspeciaisId = new MultiSelectList(db.Especiais_Modelos, "Id", "Tipo");
            ViewBag.CategoriasId = new SelectList(db.Categorias.Where(a => !a.Excluido), "Id", "Titulo");
            return View(editoriais);
        }

        //
        // GET: /Editoriais/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Editoriais editoriais = db.Editoriais.Find(id);
            if (editoriais == null)
            {
                return HttpNotFound();
            }

            ViewBag.modeloEspecial = new SelectList(db.Especiais_Modelos.Where(e => e.especial), "Id", "Tipo", (editoriais.modeloEspecial.HasValue?editoriais.modeloEspecial.Value:0));
            ViewBag.pathOriginal = pathOriginal;

            return View(editoriais);
        }

        //
        // POST: /Editoriais/Edit/5

        [HttpPost]
        public ActionResult Edit(Editoriais editoriais, HttpPostedFileBase fotoUpload, string fotoExistente = "")
        {
            if (ModelState.IsValid)
            {

                int suffix = 0;

                do
                {
                    editoriais.chave = editoriais.nome.GenerateSlug() + (suffix > 0 ? (suffix++).ToString() : "");
                    suffix++;
                } while (db.Editoriais.Where(o => o.chave == editoriais.chave && o.id != editoriais.id).Count() > 0);

                if (!string.IsNullOrEmpty(fotoExistente))
                {
                    editoriais.FotoCapa = fotoExistente;
                    ModelState.Remove("fotoUpload");
                }

                #region uploads

                if (fotoUpload != null)
                {
                    var fileOriginal = Server.MapPath(string.Format(pathOriginal, editoriais.id));
                    var path365x240 = Server.MapPath(string.Format(pathOriginal + "365x240/", editoriais.id));

                    editoriais.FotoCapa = Utils.SaveFileBase(fileOriginal, fotoUpload);

                    Utils.resizeImageAndSave3(Path.Combine(fileOriginal, editoriais.FotoCapa), 365, 240, path365x240);
                }

                db.Entry(editoriais).State = EntityState.Modified;
                db.Entry(editoriais).Property("DataCadastro").IsModified = false;
                #endregion

                db.SaveChanges();

                GerenciaLogs.saveLog(ref db, WebSecurity.GetUserId(User.Identity.Name), areaADM, TipoAcesso.Edicao, editoriais.id);

                return RedirectToAction("Index");
            }
            return View(editoriais);
        }

        //
        // GET: /Editoriais/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Editoriais editoriais = db.Editoriais.Find(id);
            if (editoriais == null)
            {
                return HttpNotFound();
            }
            return View(editoriais);
        }

        //
        // POST: /Editoriais/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Editoriais editoriais = db.Editoriais.Find(id);

            editoriais.excluido = true;
            db.Entry(editoriais).State = EntityState.Modified;

            //db.Editoriais.Remove(editoriais);

            db.SaveChanges();

            GerenciaLogs.saveLog(ref db, WebSecurity.GetUserId(User.Identity.Name), areaADM, TipoAcesso.Exclusao, editoriais.id);

            return RedirectToAction("Index");
        }
    }
}

Administrativo/Views/Editoriais/Create.cshtml
@model Administrativo.Models.Editoriais

@{
    ViewBag.Title = "Cadastrar Editoriais";
    ViewBag.Icon = "fa ";
    ViewBag.SmallDescription = "Insere um Editoriais no sistema";
}


<div class="content">
    <div class="row">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Cadastrar Editoriais</h3>
            </div>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="box-body">

                    <div class="form-group">
                        @Html.LabelFor(model => model.nome)

                        @Html.TextBoxFor(model => model.nome, new { @maxlength = 100, @class = "text-box" })
                        @Html.ValidationMessageFor(model => model.nome)
                    </div>


                    <div class="form-group">
                        <label>É uma editoria Especial?</label>
                        @Html.BooleanFieldFor(model => model.especial, false, new { @class = "form-control", style = "width: 120px;" })
                        @Html.ValidationMessageFor(model => model.especial)
                    </div>

                    <div class="form-group">
                        <label>É uma editoria de Esportes?</label>
                        @Html.BooleanFieldFor(model => model.esportes, false, new { @class = "form-control", style = "width: 120px;" })
                        @Html.ValidationMessageFor(model => model.esportes)
                    </div>

                    <div class="form-group">
                        <label>É um Canal?</label>
                        @Html.BooleanFieldFor(model => model.canal, false, new { @class = "form-control", style = "width: 120px;" })
                        @Html.ValidationMessageFor(model => model.canal)
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ativo)
                        @Html.BooleanFieldFor(model => model.ativo, true, new { @class = "form-control", style = "width: 120px;" })
                        @Html.ValidationMessageFor(model => model.ativo)
                    </div>

                    <div class="div-modelo" style="display:none">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Descricao)
                            @Html.TextBoxFor(model => model.Descricao, new { @maxlength = 512, @class = "text-box" })
                            @Html.ValidationMessageFor(model => model.Descricao)
                        </div>

                        <div class="form-group">
                            <label>Foto - <em>Resolução mínima recomendada (365x240)</em></label>

                            <input type="file" name="foto" id="foto" accept="image/*" />
                            <label id="lblFotoExistente"></label>
                            @Html.ValidationMessageFor(model => model.FotoCapa)

                            <input type="hidden" id="fotoExistente" name="fotoExistente" />
                        </div>

                        <div class="form-group">
                            <label>Modelo</label>
                            @Html.DropDownList("modeloEspecial", (SelectList)ViewBag.ModelosEspeciaisId, new { @class = "chosen-select" })
                        </div>
                    </div>



                </div>
                <div class="box-footer">
                    <input type="submit" value="Salvar" class="btn btn-success" />
                    <a href="@Url.Action("Index", "Editoriais")" class="btn btn-info">Voltar</a>

                </div>
            }
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(document).ready(function () {
            $(".chosen-select").chosen({ width: "100%" });

            $("#especial").on('change', function () {
                var value = $(this).val();
                if (value == "true") {
                    $(".div-modelo").show();
                }
                else {
                    $(".div-modelo").hide();
                }


            });

        });
    </script>
}

Administrativo/Views/Editoriais/Delete.cshtml
@model Administrativo.Models.Editoriais

@{
    ViewBag.Title = "Deletar Editoriais";
	ViewBag.Icon = "fa ";
    ViewBag.SmallDescription = "Deleta um Editoriais do sistema.";
	
}



<div class="box box-danger">
    <div class="box-header">
        <i class="fa fa-trash-o"></i>
        <h3 class="box-title">Deletar</h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
        <div class="callout callout-danger">
            <h4>Atenção</h4>
            <p>Deseja realmente deletar este registro?</p>
            @using (Html.BeginForm())
            {
                <button class="btn btn-danger">Sim</button>
                <a href="@Url.Action("Index", "Editoriais")" class="btn btn-success">Não</a>
                    
            }

        </div>
        <div class="box-content padded">
            @Html.Partial("_Details")
        </div>
    </div>
</div>

Administrativo/Views/Editoriais/Details.cshtml
@model Administrativo.Models.Editoriais

@{
    ViewBag.Title = "Editoriais";
    ViewBag.Icon = "fa ";
    ViewBag.SmallDescription = "Visualizar detalhes de Editoriais";
}

<div class="row">
    <div class="col-md-12">
        <div class="box box-info">
            <div class="box-header">
                <h3 class="box-title">Detalhes</h3>
            </div>
            <div class="box-content padded">
                @Html.Partial("_Details")
            </div>
            <div class="box-footer">



                <a href="@Url.Action("Edit","Editoriais", new { id = Model.id })" class="btn btn-warning">Editar</a>
                <a href="@Url.Action("Index","Editoriais")" class="btn btn-info">Voltar</a>
                <a href="@Url.Action("Index", "EditorialNoticias", new { editorial = Model.chave })" class="btn btn-success">Ir para Notícias</a>
                <a href="@Url.Action("Index", "Categorias", new { editorial = Model.id })" class="btn btn-info">Ir para Categorias</a>



            </div>
        </div>
    </div>
</div>

Administrativo/Views/Editoriais/Edit.cshtml
@model Administrativo.Models.Editoriais

@{
    ViewBag.Title = "Editar Editoriais";
    ViewBag.Icon = "fa ";
    ViewBag.SmallDescription = "Altere as informações de Editoriais";
}

<div class="content">
    <div class="row">
        <div class="box box-warning">
            <div class="box-header">
                <h3 class="box-title">Editar Editoriais</h3>
            </div>
            @using (Html.BeginForm("Edit", "Editoriais", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="box-body">
                    @Html.HiddenFor(model => model.id)

                    <div class="form-group">
                        @Html.LabelFor(model => model.nome)

                        @Html.TextBoxFor(model => model.nome, new { @maxlength = 100, @class = "text-box" })
                        @Html.ValidationMessageFor(model => model.nome)
                    </div>

                    <div class="form-group">
                        <label>É uma editoria Especial?</label>
                        @Html.BooleanFieldFor(model => model.especial, Model.especial, new { @class = "form-control", style = "width: 120px;" })
                        @Html.ValidationMessageFor(model => model.especial)
                    </div>

                    <div class="form-group">
                        <label>É uma editoria de Esportes?</label>
                        @Html.BooleanFieldFor(model => model.esportes, Model.esportes, new { @class = "form-control", style = "width: 120px;" })
                        @Html.ValidationMessageFor(model => model.esportes)
                    </div>

                    <div class="form-group">
                        <label>É um Canal?</label>
                        @Html.BooleanFieldFor(model => model.canal, Model.canal, new { @class = "form-control", style = "width: 120px;" })
                        @Html.ValidationMessageFor(model => model.canal)
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ativo)
                        @Html.BooleanFieldFor(model => model.ativo, Model.ativo, new { @class = "form-control", style = "width: 120px;" })
                        @Html.ValidationMessageFor(model => model.ativo)
                    </div>

                    <div class="div-modelo" style="@(Model.especial ? "" : "display:none;")">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Descricao)
                            @Html.TextBoxFor(model => model.Descricao, new { @maxlength = 512, @class = "text-box" })
                            @Html.ValidationMessageFor(model => model.Descricao)
                        </div>

                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Foto - <em>Resolução mínima recomendada (365x240)</em></label>

                                    @Html.HiddenFor(model => model.FotoCapa)
                                    <input type="file" name="fotoUpload" id="fotoUpload" onchange="javascript: $('#foto').val($(this).val().split('\\').pop());" accept="image/*" />
                                    <label id="lblFotoExistente"></label>
                                    @Html.ValidationMessageFor(model => model.FotoCapa)

                                    <input type="hidden" id="fotoExistente" name="fotoExistente" />

                                    @if (!string.IsNullOrEmpty(Model.FotoCapa))
                                    {
                                        <div><a class="text-blue btn-remove-foto" href="#"><strong>Remover Foto</strong></a></div>
                                    }
                                </div>
                            </div>
                            <div class="col-md-2">
                                @if (!string.IsNullOrEmpty(Model.FotoCapa))
                                {

                                    <a class="btn btn-block btn-primary" id="btn-imagem" data-toggle="modal" data-target="#imagem-foto" style="width: 120px;">Imagem Atual</a>

                                }
                                else
                                {
                                    <p class="text-yellow">Sem Imagem.</p>
                                }
                            </div>
                        </div>

                        <div class="form-group">
                            <label>Modelo</label>
                            @Html.DropDownList("modeloEspecial", null, "Selecione...", new { @class = "chosen-select" })
                        </div>
                    </div>

                    </div>
                <div class="box-footer">
                    <input type="submit" value="Salvar" class="btn btn-success" />
                    <a href="@Url.Action("Index", "Editoriais")" class="btn btn-info">Voltar</a>

                </div>
            }

        </div>
    </div>
</div>

<div class="modal fade" id="imagem-foto" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Imagem Atual</h4>
            </div>
            <div class="modal-body">
                @if (!string.IsNullOrEmpty(Model.FotoCapa))
                {
                    if (Model.FotoCapa.Contains("Conteudo"))
                    {
                        <img src="~/@Model.FotoCapa" width="500" />
                    }
                    else
                    {
                        <img src="@Url.Content(string.Format(ViewBag.pathOriginal,Model.id) + Model.FotoCapa)" width="500" />
                    }
                }
            </div>

            <div class="modal-footer clearfix">
                <button type="button" class="btn btn-danger" data-dismiss="modal">
                    <i class="fa fa-times"></i>Fechar
                </button>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

<script>
    $(document).ready(function () {
        $(".iframe").colorbox({ iframe: true, width: "80%", height: "80%" })

        $(".chosen-select").chosen({ width: "100%" });

        $("#especial").on('change', function () {
            var value = $(this).val();
            console.log(value);
            if (value == "true") {
                $(".div-modelo").show();
            }
            else {
                $(".div-modelo").hide();
            }
        });

        $(".btn-remove-foto").on('click', function () {
            swal({
                title: 'Exclusão',
                text: "Deseja mesmo excluir a imagem desta editoria?",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#DD6B55',
                confirmButtonText: 'Sim',
                cancelButtonText: 'Não',
            }).then(function () {
                $("#foto").val("");
                $("#btn-imagem").hide();
            }, function (dismiss) {
                if (dismiss === 'cancel') {

                }
            })
        });

        function getvalue(valor) {
            document.getElementById('fotoExistente').value = valor;
            $("#lblFotoExistente").html(valor);
            $.colorbox.close();
        }
    });
</script>
}

Administrativo/Views/Editoriais/_Details.cshtml
@model Administrativo.Models.Editoriais
<table class="table table-bordered table-striped responsive">
    <tbody>
        <tr>
            <td style="width:200px;">@Html.DisplayNameFor(model => model.id)</td>
            <td>@Html.DisplayFor(model => model.id)</td>
        </tr>

        <tr>
            <td>@Html.DisplayNameFor(model => model.nome)</td>
            <td>@Html.DisplayFor(model => model.nome)</td>
        </tr>

        <tr>
            <td>@Html.DisplayNameFor(model => model.DataCadastro)</td>
            <td>@Html.DisplayFor(model => model.DataCadastro)</td>
        </tr>
        <tr>
            <td>Categorias</td>
            <td>
                @foreach (var categoria in Model.Categorias)
                {
                    <div class="col-md-3 col-sm-4">
                        <i class="fa fa-fw fa-user"></i>@categoria.Titulo
                    </div>
                }

                @Html.Raw((Model.Categorias.Count() == 0 ? "<p class=\"text-yellow\">Nenhuma categoria cadastrada.</p>" : ""))
            </td>
        </tr>

    </tbody>
</table>