Site/Models/RedesSociais.cs
namespace Site.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class RedesSociais
    {
        public int Id { get; set; }

        public int TipoRede { get; set; }

        [StringLength(400)]
        public string Imagem { get; set; }

        public string Texto { get; set; }

        [StringLength(800)]
        public string Link { get; set; }

        public DateTime? Data { get; set; }

        public DateTime DataCadastro { get; set; }

        public string Video { get; set; }

        public string PostId { get; set; }
    }
}

Site/ViewModels/FooterViewModel.cs
using Site.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Site.ViewModels
{
    public class FooterViewModel
    {
        public List<EditoriasLayoutViewModel> Editoriais { get; set; }
    }

}

Site/ViewModels/NavigationBarViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Site.ViewModels
{
    public class NavigationBarViewModel
    {
        public List<EditoriasLayoutViewModel> especiais { get; set; }
        public List<EditoriasLayoutViewModel> canais { get; set; }
    }
}

Site/ViewModels/RedesSociaisViewModel.cs
using Site.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Site.ViewModels
{
    public class RedesSociaisViewModel
    {

    }

    public class RedesSociaisHomeViewModel
    {
        public List<RedesSociais> Twitter { get; set; }
        public List<RedesSociais> Facebook { get; set; }
        public RedesSociais FotoDestaque{ get; set; }
    }

}

Site/Controllers/LayoutController.cs
using Site.Enums;
using Site.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data;
using System.Web;
using System.Web.Mvc;
using Site.Services;

namespace Site.Controllers
{
    public class LayoutController : BaseController
    {
        private string primeKey = "layout:";
        // GET: Layout
        public PartialViewResult Menu()
        {
            var retorno = MenuCached();

            return PartialView("_Menu", retorno);
        }
        public PartialViewResult Header()
        {
            var retorno = MenuCached();

            return PartialView("_Header", retorno);
        }
        private MenuViewModel MenuCached()
        {
            string key = primeKey + "Menu:TRadios:TEditoriais:TCategoriasAudios";

            Func<object, MenuViewModel> funcao = t => MenuDB();
            var retorno = RedisService.GetOrSetToRedis(key, funcao, 300);
            return retorno;
        }
        private MenuViewModel MenuDB()
        {
            var radios = db.Radios.Where(x => x.Ativo).OrderBy(x => x.Titulo).Select(r => new RadiosMenuViewModel { Chave = r.Chave, Titulo = r.Titulo, Stream1 = r.Stream1, Stream2 = r.Stream2 }).ToList();
            var editorias = db.Editoriais.Where(x => x.ativo && !x.especial & !x.excluido && !x.esportes && x.chave != "ouvintes-no-ar").OrderBy(x => x.nome).Select(e => new EditoriasLayoutViewModel { chave = e.chave, nome = e.nome }).ToList();
            var campeonatos = db.Editoriais.Where(x => x.ativo && !x.especial & !x.excluido && x.esportes && x.Action != null).OrderBy(x => x.nome).Select(e => new EditoriasLayoutViewModel { Action = e.Action, nome = e.nome }).ToList();
            var categorias = db.CategoriasAudios.Where(x => x.Liberado && !x.Excluido).OrderBy(x => x.Descricao).Select(a => new CategoriasAudiosMenuViewModel { Descricao = a.Descricao, Id = a.Id }).ToList();

            var diaS = (int)DateTime.Now.DayOfWeek;
            var horaAtual = string.Format("{0:HH:mm tt}", DateTime.Now);

            var programacoesDia = db.Horario_programacao.Where(x => x.diaSemana == diaS).Select(y => new ProgramacoesVM { programaId = y.idPrograma.ToString(), horario = y.horario, Data = new DateTime() }).ToList();
            foreach (var item in programacoesDia)
            {
                item.Data = DateTime.Parse(DateTime.Now.ToShortDateString() + " " + item.horario);
            }

            var atual = programacoesDia.OrderBy(x => x.Data).LastOrDefault(x => x.Data <= DateTime.Now);
            var horarioFinal = programacoesDia.OrderBy(x => x.Data).Where(x => x.Data >= DateTime.Now).Take(2).FirstOrDefault();
			if (atual != null)
			{
				var convertId = Int32.Parse(atual.programaId);

				var hf = "";
				if (horarioFinal != null)
				{
					hf = horarioFinal.horario;
				}

				var programaAtual = db.Programacao.Where(x => x.id == convertId).Select(a => new ProgramacaoMenuViewModel { Id = a.id, Horario = atual.horario, FimHorario = hf, Nome = a.nome }).ToList();

				var viewModel = new MenuViewModel
				{
					Editorias = editorias,
					Radios = radios,
					Campeonatos = campeonatos,
					CategoriasAudios = categorias,
					Programacao = programaAtual
				};
				return viewModel;
			}
			else
				return null;
        }

        public PartialViewResult MenuEspeciais()
        {
            var retorno = EditoriaisLayoutCached();

            return PartialView("_NavigationBar", retorno);
        }
        public PartialViewResult Footer()
        {
            var retorno = EditoriaisLayoutCached();

            return PartialView("_Footer", new FooterViewModel { Editoriais = retorno });
        }
        private List<EditoriasLayoutViewModel> EditoriaisLayoutCached()
        {
            string key = primeKey + "EditoriaisLayoutCached:TEditoriais";

            Func<object, List<EditoriasLayoutViewModel>> funcao = t => MenuEspeciaisDB();
            var retorno = RedisService.GetOrSetToRedis(key, funcao, 300);

            return retorno;
        }
        private List<EditoriasLayoutViewModel> MenuEspeciaisDB()
        {
            var editoriais = db.Editoriais.Where(x => !x.excluido && x.ativo && x.especial)
                .OrderByDescending(x => x.DataCadastro)
                .Select(e => new EditoriasLayoutViewModel {
                    Action = e.Especiais_Modelos != null ? e.Especiais_Modelos.Action : "",
                    chave = e.chave,
                    nome = e.nome,
                    Canal = e.canal,
                    Especial = e.especial
                }).ToList();

            return editoriais;
        }
        
        public PartialViewResult RedesSociais()
        {
            string key = primeKey + "RedesSociais:TRedesSociais";

            Func<object, RedesSociaisHomeViewModel> funcao = t => RedesSociaisDB();
            var retorno = RedisService.GetOrSetToRedis(key, funcao, 60);


            return PartialView("_RedesSociais", retorno);
        }
        private RedesSociaisHomeViewModel RedesSociaisDB()
        {
            var redesTwitter = db.RedesSociais.Where(x => (RedeSocialTipo)x.TipoRede == RedeSocialTipo.Twitter).Take(2).OrderByDescending(x => x.Data);
            var redesFace = db.RedesSociais.Where(x => (RedeSocialTipo)x.TipoRede == RedeSocialTipo.Facebook && x.Texto != null).Take(2).OrderByDescending(x => x.Data);
            var redesFoto = db.RedesSociais.Where(x => (RedeSocialTipo)x.TipoRede == RedeSocialTipo.Facebook && x.Texto == null).OrderByDescending(x => x.Data).FirstOrDefault();

            var viewModelRedes = new RedesSociaisHomeViewModel
            {
                Facebook = redesFace.ToList(),
                Twitter = redesTwitter.ToList(),
                FotoDestaque = redesFoto
            };

            return viewModelRedes;
        }

        private class ProgramacoesVM
        {
            public string programaId { get; set; }
            public string horario { get; set; }
            public DateTime? Data { get; set; }
        }

    }
}

Site/Controllers/RedesSociaisController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Site.Enums;
using System.Globalization;
using System.Threading.Tasks;
using Site.Helpers;
using Site.Controllers;
using Site.Models;

namespace Site.Controllers
{
    public class RedesSociaisController : BaseController
    {
        [OutputCache(Duration = 600, Location = System.Web.UI.OutputCacheLocation.Server)]
        public JsonResult AtualizaRedesSociais()
        {
            //Task<string> str = Task.Run(async () =>
            //{
            //    string msg = await getPostsSocialAsync();
            //    return msg;
            //});
        
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        #region async
        private Task<string> getPostsSocialAsync()
        {
            return Task.Run<string>(() => getPostsSocial());
        }
        #endregion

        #region metodoGeral
        public string getPostsSocial()
        {
            #region RedesSociaisApi


            List<RedeSocialModel> listaPosts = new List<RedeSocialModel>();

            //Instagram
            //try
            //{
            //    listaPosts.AddRange(getJsonInstagram(ConfigurationManager.AppSettings["instagramAccessToken"]));
            //}
            //catch { }


            //Facebook
            try
            {

                listaPosts.AddRange(getJsonFacebook(ConfigurationManager.AppSettings["facebookUserId"]));
            }
            catch { }


            //Twitter
            try
            {
                listaPosts.AddRange(getJsonTwitter(ConfigurationManager.AppSettings["twitterUser"]));
            }
            catch (Exception ex)
            {
                var x = ex;

            }


            //youtube

            /*
                try
                {
                    listaPosts.AddRange(getJsonYoutube(ConfigurationManager.AppSettings["YoutubeUser"]));
                }
                catch (Exception ex)
                {
                    var x = ex;

                }
            */

            var lista = listaPosts.OrderByDescending(d => d.DataPublicacaoOrder);


            foreach (var item in lista)
            {
                var obj = new RedesSociais();
                obj.Imagem = item.Picture;
                obj.PostId = item.PostId;
                obj.Link = item.Link;
                obj.Texto = item.Mensagem;
                obj.TipoRede = item.TipoRedeSocial.GetHashCode();
                obj.Video = item.Video;
                obj.Data = item.DataPublicacaoOrder;
                obj.DataCadastro = DateTime.Now;


                var db2 = new ModeloDados();

                var exists = db2.RedesSociais.FirstOrDefault(x => x.PostId == obj.PostId && x.TipoRede == obj.TipoRede);

                if (exists == null)
                {
                    db2.RedesSociais.Add(obj);
                    db2.SaveChanges();
                }


            }

            return "";
            
            #endregion
        }
        #endregion

        #region metodos individuais

        public List<RedeSocialModel> getJsonInstagram(string accessToken)
        {
            var url2 = "https://api.instagram.com/v1/users/self/media/recent/?access_token="+accessToken;

            List<RedeSocialModel> retorno = new List<RedeSocialModel>();
          
            HttpWebRequest request = (HttpWebRequest)WebRequest.Create(url2);
            WebResponse response = request.GetResponse();
            using (Stream responseStream = response.GetResponseStream())
            {
                StreamReader reader = new StreamReader(responseStream, Encoding.UTF8);
                string retornoInsta = reader.ReadToEnd();
                var requests = JsonConvert.DeserializeObject<dynamic>(retornoInsta);

                    if (requests.data.Count > 0)
                    {
                        foreach (var item in requests.data)
                        {
                            DateTime dateTime = new DateTime(1970, 1, 1, 0, 0, 0, 0, System.DateTimeKind.Utc);
                            dateTime = dateTime.AddSeconds(Convert.ToDouble(item.created_time.ToString())).ToLocalTime();

                            string data = String.Format("{0:dd/MM/yyyy HH:mm:ss}", dateTime);
                            
                            retorno.Add(new RedeSocialModel()
                            {
                                TipoRedeSocial = RedeSocialTipo.Instagram,
                                PostId = item.id,
                                Mensagem = item.caption.text,
                                Picture = item.images.low_resolution.url,
                                Video = item.type == "video" ? item.videos.low_resolution.url : "",
                                Link = item.link,
                                dataPublicacao = data
                            });
                        
                        }
                    }
               
              
              

            }
            return retorno;

        }
        
        public List<RedeSocialModel> getJsonFacebook(string userid)
        {
            //Parkshopping - 141048155937027
            string apiKey = ConfigurationManager.AppSettings["facebookAccessToken"];
            List<RedeSocialModel> retorno = new List<RedeSocialModel>();
            //https://graph.facebook.com/141048155937027/posts?access_token=914701921932420|kb3JkWmBZlCXaBK9kPh8HJnqyIA&fields=message,picture,source,link,created_time
            HttpWebRequest request = (HttpWebRequest)WebRequest.Create(@"https://graph.facebook.com/" + userid + "/posts?access_token=" + apiKey + "&fields=message,full_picture,source,link,created_time,type,permalink_url");
            WebResponse response = request.GetResponse();
            using (Stream responseStream = response.GetResponseStream())
            {
                StreamReader reader = new StreamReader(responseStream, Encoding.UTF8);
                string retornoFace = reader.ReadToEnd();
                var requests = JsonConvert.DeserializeObject<dynamic>(retornoFace);

                //requests.AddRange(requestFb);

                if (requests.data.Count > 0)
                {
                    foreach (var item in requests.data)
                    {
                        retorno.Add(new RedeSocialModel()
                        {
                            TipoRedeSocial = RedeSocialTipo.Facebook,
                            PostId = item.id,
                            Mensagem = item.message,
                            Picture = item.full_picture,
                            Video = item.type == "video" ? item.source : "",
                            Link = item.permalink_url,
                            dataPublicacao = Convert.ToDateTime(item.created_time.ToString()).ToString()
                        });
                    }
                }


            }

            return retorno;
        }

        public List<RedeSocialModel> getJsonTwitter(string userid)
        {
            List<RedeSocialModel> retornoPosts = new List<RedeSocialModel>();

            string strJson = Tweet.AuthTwitter(userid);
            if (!String.IsNullOrEmpty(strJson))
            {
                var retorno = JsonConvert.DeserializeObject<dynamic>(strJson);
                if (retorno.Count > 0)
                {
                    foreach (var item in retorno)
                    {
                        retornoPosts.Add(
                            new RedeSocialModel()
                            {
                                TipoRedeSocial = RedeSocialTipo.Twitter,
                                PostId = item.id,
                                Mensagem = item.text,
                                Picture = item.entities.media != null ? item.entities.media[0].media_url_https : "",
                                Video = "",
                                Link = item.entities.media != null ? item.entities.media[0].url : "",
                                dataPublicacao = DateTime.ParseExact(item.created_at.ToString(), "ddd MMM dd HH:mm:ss zzzz yyyy", CultureInfo.InvariantCulture).ToString()
                            });
                    }
                }
            }

            return retornoPosts.OrderByDescending(x => x.dataPublicacao).ToList();
        }
        
        public List<RedeSocialModel> getJsonYoutube(string userid)
        {
            //Parkshopping - 141048155937027
            string apiKey = ConfigurationManager.AppSettings["facebookClientId"];
            List<RedeSocialModel> retorno = new List<RedeSocialModel>();


            var preRequest = (HttpWebRequest)WebRequest.Create(@"https://www.googleapis.com/youtube/v3/channels?key=AIzaSyDr8YEwMkzF-zDt8ATOFDOwIbF-JqXCTOg&forUsername=" + userid + "&part=id");

            var preResponse = preRequest.GetResponse();

            var hashCanal = "";

            using (var responseStream = preResponse.GetResponseStream())
            {
                var reader = new StreamReader(responseStream, Encoding.UTF8);
                var retornoFace = reader.ReadToEnd();
                var requests = JsonConvert.DeserializeObject<dynamic>(retornoFace);

                if (requests.items != null)
                {
                    foreach (var item in requests.items)
                    {
                        hashCanal = item.id;
                    }
                }
            }

            var request = (HttpWebRequest)WebRequest.Create(@"https://www.googleapis.com/youtube/v3/search?key=AIzaSyDr8YEwMkzF-zDt8ATOFDOwIbF-JqXCTOg&channelId=" + hashCanal + "&part=snippet&order=date");

            var response = request.GetResponse();

Site/Views/Shared/_Copa.cshtml
@{
    var faltam = new DateTime(2018, 6, 14) - DateTime.Now;
    var dia = faltam.Days.ToString("000");
    var horas = faltam.Hours.ToString("00");
    var minutos = faltam.Minutes.ToString("00");
}
<div class="container-copa">
    <div class="contador-copa">
        <div class="bg-copa"></div>
        <div class="container-textos">
            <p class="tit-faltam">FALTAM</p>
            <p class="cnt-regressiva">@dia @horas @minutos</p>
            <p class="cnt-dias">DIAS HRS MIN</p>
        </div>
    </div>
    <div class="container-footer-copa">
        <img src="~/Content/footer-copa.png" alt="Rádio CompanyName" />
    </div>
</div>

Site/Views/Shared/_Layout.cshtml
@using Site.Helpers
<!doctype html>
<html xml:lang="pt-br" lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <meta name="author" content="Rádio CompanyName - A Rádio de Minas " />
    <meta name="description" content="" />
    <meta name="resource-type" content="document" />
    <meta name="content-language" content="pt-br" />
    <meta name="revisit" content="1 day" />
    <meta name="ICBM" content="-20.8341668,-45.51577" />
    <META NAME="ROBOTS" CONTENT="INDEX, FOLLOW">

    @RenderSection("SEO", required: false)
    <meta property="fb:app_id" content="215909845518383" />
    <!-- Google Tag Manager Produção -->
    <script>
        (function (w, d, s, l, i) {
            w[l] = w[l] || []; w[l].push({
                'gtm.start':
                    new Date().getTime(), event: 'gtm.js'
            }); var f = d.getElementsByTagName(s)[0],
                j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : ''; j.async = true; j.src =
                'https://www.googletagmanager.com/gtm.js?id=' + i + dl; f.parentNode.insertBefore(j, f);
        })(window, document, 'script', 'dataLayer', 'GTM-T6B7RPX');
    </script>
    <!-- End Google Tag Manager -->
    <!-- Google Tag Manager Homologação -->
    @*<script>
            (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
            })(window, document, 'script', 'dataLayer', 'GTM-WHP3FTK');
        </script>*@
    <!-- End Google Tag Manager -->
	
    <!-- Navegg -->
    <script id="navegg" type="text/javascript" src="https://tag.navdmp.com/tm46204.js"></script>
    <!-- End Navegg -->

    <link rel="shortcut icon" href="~/images/favicon.png" type="image/x-icon">
    <link rel="shortcut icon" href="~/images/favicon.ico" type="image/x-icon">
    <link rel="apple-touch-icon" href="~/images/touch-icon-iphone.png" />
    <link rel="apple-touch-icon" sizes="72x72" href="~/images/touch-icon-ipad.png" />
    <link rel="apple-touch-icon" sizes="114x114" href="~/images/touch-icon-iphone-retina.png" />


    @Styles.Render("~/Content/css-application")
    @Scripts.Render("~/bundles/jquery")

    <style>
        @@media (max-width:799px) {
            .margem-topo {
                height: 130px;
            }
        }
        @@media (min-width:800px) {
            .margem-topo {
                height: 320px;
            }
        }
    </style>
    <!--[if lt IE 9]>
        <script src="~/scripts/html5shiv.js"></script>
    <![endif]-->


    @RenderSection("css", required: false)
</head>

<body class="home-page">
    <div id="margem-topo" class="margem-topo"></div>
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-12157365-1', 'auto');
        ga('send', 'pageview');
    </script>

    <div id="fb-root"></div>
    <script>
        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/pt_BR/sdk.js#xfbml=1&version=v2.8&appId=545713468800917";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>
    <!-- Google Analitycs     -->
    <!-- Google Tag Manager (noscript) Produção -->
    <noscript>
        <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-T6B7RPX"
                height="0" width="0" style="display:none;visibility:hidden"></iframe>
    </noscript>
    <!-- End Google Tag Manager (noscript) -->
    <!-- Google Tag Manager (noscript) Homologação -->
    @*<noscript>
        <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-WHP3FTK"
                height="0" width="0" style="display:none;visibility:hidden"></iframe>
    </noscript>*@
    <!-- End Google Tag Manager (noscript) -->
    @*<script>
                (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
                })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

                ga('create', 'UA-86304380-1', 'auto');
                ga('send', 'pageview');
        </script>*@

    <header class="main-header" role="banner">

        @{Html.RenderAction("Header", "Layout");}

        @{Html.RenderAction("Menu", "Layout");}

        @{Html.RenderAction("MenuEspeciais", "Layout");}

    </header>


    @RenderBody()

    @{Html.RenderAction("RedesSociais", "Layout");}

    @{Html.RenderAction("Footer", "Layout");}

</body>
</html>

@Scripts.Render("~/bundles/scripts")
@RenderSection("scripts", required: false)
@RenderSection("script_seubolso", required: false)

<script>
    //var overiFrame = -1;
    //$('.banner-iframe iframe').hover(function () {
    //    overiFrame = $(this).closest('.banner').attr('bannerid');
    //}, function () {
    //    overiFrame = -1;
    //});
    //$(window).blur(function () {
    //    if (overiFrame !== -1)
    //        $('.banner-iframe').click();
    //    setTimeout(function () { window.focus(); }, 0);
    //});

    $(document).ready(function () {
        streaming('@Url.Action("LiveAtual", "LiveStreaming")')
        busca('@ViewContext.RouteData.Values["busca"]');
        previsaoTempo('@Url.Action("Previsao", "Tempo")');
        layout();
    });
</script>

Site/Views/Shared/_NavigationBar.cshtml
@model List<Site.ViewModels.EditoriasLayoutViewModel>


<div class="navigation-bottom">
    <button class="button" id="nav-bottom">
        <i class="fa fa-caret-square-o-down"></i>
        <span>Especiais</span>
    </button>

    <nav class="center">
        <span>Reportagens Especiais:</span>
        @*<a href="@Url.Action("ReportagensEspeciais", "Especiais")">Reportagens Especiais</a>*@
        @if (Model != null && Model.Count > 0)
        {
            foreach (var item in Model)
            {
                if (item.chave.Contains("bh") || item.chave.Contains("parlamento") || item.chave.Contains("pampulha") || item.chave.Contains("carnaval") || item.chave.Contains("veiculos") || item.chave.Contains("ingressos"))
                {
                    <a href="@Url.Action(item.Action, "Especiais")">@item.nome</a>
                }
                else
                {
                    <a href="@Url.Action(item.Action, "Especiais", new { chave = item.chave })">@item.nome</a>
                }
            }
        }
    </nav>
</div>

Site/Views/Shared/_RedesSociais.cshtml
@using Site.Helpers
@model Site.ViewModels.RedesSociaisHomeViewModel

<section class="widgets-social">
    <div class="center">
        <header>
            <h2>#CompanyNameNasRedes</h2>
            <div class="links">
                <span>Siga-nos</span>
                <a href="https://www.facebook.com/radioCompanyName/?fref=ts" class="icons" target="_blank" title="Curta nossa página no Facebook">
                    <i class="fa fa-facebook"></i>
                </a>
                <a href="https://twitter.com/radioCompanyName?lang=pt" class="icons" target="_blank" title="Siga-nos no Twitter">
                    <i class="fa fa-twitter"></i>
                </a>
            </div>
        </header>


        @if (Model.Facebook.Count > 0 && Model.Twitter.Count > 0)
        {
            <div class="box clearfix">
                <div class="content-articles-social">

                    <div class="wrapper" id="twitter-post">
                        @foreach (var item in Model.Twitter)
                        {
                            <article class="block tw">
                                <h2>RadioCompanyName</h2>
                                <p>@(!string.IsNullOrEmpty(item.Texto)?Utils.TruncateText(item.Texto,178,true):"")</p>
                                <a href="@item.Link" target="_blank">Acessar Link</a>
                            </article>
                        }
                        
                    </div>

                    <div class="wrapper" id="fb-post">
                        @foreach (var item in Model.Facebook)
                        {
                            <article class="block fb">
                                <h2>RadioCompanyName</h2>
                                <p>@(!string.IsNullOrEmpty(item.Texto) ? Utils.TruncateText(item.Texto,178,true) : "")</p>
                                <a href="@item.Link" target="_blank">Acessar Link</a>
                            </article>
                        }
                        
                    </div>
                </div>


                @if (Model.FotoDestaque != null)
                {
                    <article class="featured-box" id="fb-big">
                        <a href="@Model.FotoDestaque.Link" target="_blank">
                            <img src="@Model.FotoDestaque.Imagem" alt="@Model.FotoDestaque.Texto" width="313" height="314" title="@Model.FotoDestaque.Texto">
                        </a>
                    </article>
                }
                

            </div>
        }



    </div>
</section>