Administrativo/Models/Logs.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int AreaId { get; set; }
        public int Acao { get; set; }
        public string IP { get; set; }
        public Nullable<int> Detalhes { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual AreasADM AreasADM { get; set; }
    }
}

Administrativo/Controllers/LogsController.cs
using Administrativo.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Administrativo.Controllers
{
    public class LogsController : BaseController
    {
        //
        // GET: /Logs/

        public ActionResult Index(int? page, string search = "", string sortField = "", string order = "", int AreaId = 0, int UserId = 0)
        {

            ViewBag.EditoriaisActive = "active";
            ViewBag.EditoriaisSubActive = "active";
            ViewBag.Search = search;
            ViewBag.Order = order;
            ViewBag.SortField = sortField;
            ViewBag.Page = page;
            ViewBag.AreaIdVB = AreaId;
            ViewBag.UserIdVB = UserId;
            allClassOffSort();

            ViewBag.AreaId = new SelectList(db.AreasADM.Where(c=>c.Id>1 ), "Id", "Area");
            ViewBag.UserId = new SelectList(_db.UserProfiles, "UserId", "UserName");

            return View(GetListItens(page, search, sortField, order, AreaId, UserId));

        }


        public void allClassOffSort()
        {

            ViewBag.SortClassid = "sorting";
            ViewBag.SortClassnome = "sorting";
            ViewBag.SortClassDataCadastro = "sorting";

        }

        public IPagedList<Logs> GetListItens(int? page, string searchParam = "", string sortField = "", string order = "", int AreaId = 0, int UserId = 0)
        {
            var list = db.Logs;

            var pagedList = from obj in list select obj;
            int pageNumber = (page ?? 1);


            if (!string.IsNullOrEmpty(searchParam))
            {
                int outDate = 0;
                int id = int.TryParse(searchParam, out outDate) ? int.Parse(searchParam) : 0;
                pagedList = pagedList.Where(e => e.Id == id || e.AreasADM.Area.ToLower().Contains(searchParam.ToLower()));
            }

            if (AreaId > 0)
            {
                pagedList = pagedList.Where(x => x.AreaId == AreaId);
            }


            if (UserId > 0)
            {
                pagedList = pagedList.Where(x => x.UserId == UserId);
            }

            switch (sortField)
            {
                case "id":
                    if (order == "ASC")
                    {
                        pagedList = pagedList.OrderBy(e => e.Id);
                        ViewBag.SortClassid = "sorting_asc";

                    }
                    else
                    {
                        pagedList = pagedList.OrderByDescending(e => e.Id);
                        ViewBag.SortClassid = "sorting_desc";
                    }
                    break;
                case "nome":
                    if (order == "ASC")
                    {
                        pagedList = pagedList.OrderBy(e => e.AreasADM.Area);
                        ViewBag.SortClassnome = "sorting_asc";

                    }
                    else
                    {
                        pagedList = pagedList.OrderByDescending(e => e.AreasADM.Area);
                        ViewBag.SortClassnome = "sorting_desc";
                    }
                    break;
                case "DataCadastro":
                    if (order == "ASC")
                    {
                        pagedList = pagedList.OrderBy(e => e.Data);
                        ViewBag.SortClassDataCadastro = "sorting_asc";

                    }
                    else
                    {
                        pagedList = pagedList.OrderByDescending(e => e.Data);
                        ViewBag.SortClassDataCadastro = "sorting_desc";
                    }
                    break;
                default:
                    pagedList = pagedList.OrderByDescending(e => e.Data);
                    ViewBag.SortClassid = "sorting_asc";
                    break;
            }

            return pagedList.ToPagedList<Logs>(pageNumber, 10);
        }

        //
        // GET: /Logs/Details/5

        public ActionResult Details(int id)
        {
            var log = db.Logs.FirstOrDefault(x => x.Id == id);

            if (log == null)
            {
                return HttpNotFound();
            }


            return View(log);
        }


        //
        // GET: /Logs/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Logs/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public string getUserName(int UserId)
        {
            var name = _db.UserProfiles.FirstOrDefault(x => x.UserId == UserId).UserName;
            return name;
        }
    }
}

Administrativo/Views/Logs/Details.cshtml
@using Administrativo.Helpers
@using Administrativo.Enums
@model Administrativo.Models.Logs

@{
    ViewBag.Title = "Detalhe do Log";
    ViewBag.Icon = "fa ";
    ViewBag.SmallDescription = "Visualizar detalhes do log selecionado";
    var obj = new Administrativo.Controllers.LogsController();
    var username = obj.getUserName(Model.UserId);
}

<div class="row">
    <div class="col-md-12">
        <div class="box box-info">
            <div class="box-header">
                <h3 class="box-title">Detalhes</h3>
            </div>
            <div class="box-content padded">
                 <table class="table table-bordered table-striped responsive">
                    <tbody>
                        <tr>
                            <td style="width:200px;">@Html.DisplayNameFor(model => model.Id)</td>
                            <td>@Html.DisplayFor(model => model.Id)</td>
                        </tr>

                        <tr>
                            <td>Usuário</td>
                            <td>@username</td>
                        </tr>

                        <tr>
                            <td>Area acessada</td>
                            <td>@Model.AreasADM.Area</td>
                        </tr>
                        <tr>
                            <td>Ação realizada</td>
                            <td>@(GerenciaLogs.GetDescriptionFromEnumValue((TipoAcesso)Model.Acao))</td>
                        </tr>
                        @if (Model.Detalhes.HasValue)
                        {
                            <tr>
                                <td>Id do item</td>
                                <td>@Model.Detalhes.Value</td>
                            </tr>
                        }
                        <tr>
                            <td>IP</td>
                            <td>@Model.IP</td>
                        </tr>
                        <tr>
                            <td>Data e Hora</td>
                            <td>@Model.Data.ToShortDateString() às @Model.Data.ToShortTimeString()</td>
                        </tr>

                    </tbody>
                </table>
            </div>
            <div class="box-footer">
                <a href="@Url.Action("Index","Logs")" class="btn btn-info">Voltar</a>
            </div>
        </div>
    </div>
</div>

Administrativo/Views/Logs/Index.cshtml
@using Administrativo.Helpers
@using PagedList
@using PagedList.Mvc
@using Administrativo.Enums

@model IPagedList<Administrativo.Models.Logs>

@{
    ViewBag.Title = "Logs de alterações no sistema";
    ViewBag.Icon = "fa ";
    ViewBag.SmallDescription = "Lista de operações realizadas no sistema";
    var obj = new Administrativo.Controllers.LogsController();

}

<div class="row">
    <div class="col-md-12">
        <div class="box box-info">
            <div class="box-header">
                <h3 class="box-title">Lista</h3>
            </div>
            <div class="box-body no-padding">
                <div class="fc fc-ltr">
                    @using (Html.BeginForm())
                    {
                        <table class="fc-header" style="width: 100%;">
                            <tbody>
                                <tr style="height: 48px;">
                                    <td class="fc-header-left" style="width: 10px;"></td>
                                    <td class="fc-header-center">
                                        @Html.TextBox("Search", null, new { @class = "text-box", placeholder = "Busca" })
                                    </td>

                                    <td class="fc-header-left" style="width:250px;">
                                        @Html.DropDownList("AreaId", null, "Filtrar por area...", new { @class = "chosen-select" })
                                    </td>

                                    <td class="fc-header-left" style="width:200px;">
                                        @Html.DropDownList("UserId", null, "Filtrar por usuario...", new { @class = "chosen-select" })
                                    </td>
                                    <td class="fc-header-right">
                                        <input type="submit" value="Enviar" class="btn bg-olive margin" style="margin: 0px;" />
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    }
                    <table class="table table-striped responsive table-hover dataTable">
                        <thead>
                            <tr role="row">
                                <th style="width:40px;" onclick="document.location='@Url.Action("Index", new { sortField = "id", order = @ViewBag.Order == "DESC" ? "ASC" : "DESC", page = ViewBag.Page, search = ViewBag.Search })'" class="@ViewBag.SortClassid">
                                    @Html.DisplayNameFor(model => model.First().Id)
                                </th>
                                <th onclick="document.location='@Url.Action("Index", new { sortField = "nome", order = @ViewBag.Order == "DESC" ? "ASC" : "DESC", page = ViewBag.Page, search = ViewBag.Search })'" class="@ViewBag.SortClassnome">
                                    Usuario
                                </th>

                                <th onclick="document.location='@Url.Action("Index", new { sortField = "nome", order = @ViewBag.Order == "DESC" ? "ASC" : "DESC", page = ViewBag.Page, search = ViewBag.Search })'" class="@ViewBag.SortClassEspecial">
                                    Area
                                </th>

                                <th onclick="document.location='@Url.Action("Index", new { sortField = "esportes", order = @ViewBag.Order == "DESC" ? "ASC" : "DESC", page = ViewBag.Page, search = ViewBag.Search })'" class="@ViewBag.SortClassEsportes">
                                    Ação
                                </th>
                               
                                <th style="width: 150px;" onclick="document.location='@Url.Action("Index", new { sortField = "DataCadastro", order = @ViewBag.Order == "DESC" ? "ASC" : "DESC", page = ViewBag.Page, search = ViewBag.Search })'" class="@ViewBag.SortClassDataCadastro">
                                    @Html.DisplayNameFor(model => model.First().Data)
                                </th>
                                <th style="width: 222px;">Ações</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model.TotalItemCount > 0)
                            {
                                foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Id)
                                        </td>
                                        <td>
                                            @obj.getUserName(item.UserId)
                                        </td>
                                        <td>
                                            @item.AreasADM.Area
                                        </td>
                                        <td>
                                            @(GerenciaLogs.GetDescriptionFromEnumValue((TipoAcesso)item.Acao))
                                        </td>
                                        
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Data)
                                        </td>
                                        <td>
                                            <div class="btn-group">                                               
                                                <a href="@Url.Action("Details", new { id = item.Id })" class="btn bg-olive btn-small">
                                                    <i class="fa fa-search-plus"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                }
                            }
                            else
                            {
                                <tr>
                                    <td colspan="6" align="center">Nenhum registro encontrado.</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="box-footer clearfix no-border">
                @if (Model.PageCount > 1)
                {
                    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, search = ViewBag.Search, order = ViewBag.Order, SortField = ViewBag.SortField ,  AreaId = ViewBag.AreaIdVB , UserId = ViewBag.UserIdVB }), PagedListRenderOptions.OnlyShowFivePagesAtATime)
                }
            </div>
        </div>
    </div>
</div>

@section Scripts {

    <script type="text/javascript">
        $(document).ready(function () {
            $(".chosen-select").chosen({ width: "100%" });
        });
    </script>

}