Site/ViewModels/SeuBolso/BannerSeuBolsoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Site.ViewModels.SeuBolso
{
    public class BannerSeuBolsoViewModel
    {
        public int Id { get; set; }
        public string Anunciante { get; set; }
        public string Titulo { get; set; }
        public string Arquivos { get; set; }
        public string Link { get; set; }
        public string Chave { get; set; }
        public string AreaBannerTamanho { get; set; }
        public string AreaBannerDescricao { get; set; }
        public bool? AreaBannerAtivo { get; set; }
    }
}

Site/ViewModels/SeuBolso/IndicadoresViewModel.cs
using Site.Models;
using System.Collections.Generic;

namespace Site.ViewModels.SeuBolso {
    public class IndicadoresViewModel {
        public IndicadoresBovespa Bovespa { get; set; }
        public List<IndicadorFinanceiro> Financeiros { get; set; }
    }
}

Site/ViewModels/SeuBolso/SeuBolsoViewModel.cs
using PagedList;
using Site.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Site.ViewModels.SeuBolso
{
    public class SeuBolsoViewModel
    {
        public List<BannerSeuBolsoViewModel> Banners { get; set; }
        public IPagedList<NoticiasViewModel> Noticias { get; set; }
        public IndicadoresViewModel Indicadores { get; set; }
        public List<MoedaValor> MoedasValor { get; set; }
    }
}

Site/Controllers/SeuBolsoController.cs
using Site.ViewModels.SeuBolso;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using Site.Services;
using Site.Helpers;
using Site.ViewModels;
using Site.Models;
using System.Threading.Tasks;
using PagedList;

namespace Site.Controllers
{
    public class SeuBolsoController : BaseController
    {

        private const string CHAVE_EDITAL = "banco-inter";

        public SeuBolsoController()
        {
           // db.Configuration.LazyLoadingEnabled = false;
        }


        // GET: SeuBolso
        string primeKey = "seubolso:";
        public ActionResult Index(int page = 1, string palavraChave = null, string dataInicio = null, string dataFinal = null)
        {
            //Iniciando variáveis
            var retorno = new SeuBolsoViewModel();

            //Carregando o VM com os dados das rotinas que vão no banco e no Redis
            retorno.Banners = BannersCached();
            retorno.Noticias = RetornaNoticiasCached(palavraChave, page, dataInicio, dataFinal).ToPagedList(page,9);
            retorno.Indicadores = RetornaIndicadores();

            return View(retorno);
        }
        
        private IndicadoresViewModel RetornaIndicadores() {
            string keyBanner = primeKey + "Index:Indicadores:TIndicadoresBovespa:TIndicadorFinanceiro";

            Func<object, IndicadoresViewModel> funcao = t => RetornaIndicadoresCached();
            return RedisService.GetOrSetToRedis(keyBanner, funcao, 30);
        }
        private IndicadoresViewModel RetornaIndicadoresCached() {
            return new IndicadoresViewModel {
                Bovespa = db.IndicadoresBovespa.FirstOrDefaultAsync().Result,
                Financeiros = db.IndicadoresFinanceiros.Where(x => x.Liberado).ToListAsync().Result
            };
        }

        private List<NoticiasViewModel> RetornaNoticiasCached(string text,int page, string dataInicio = null, string dataFinal = null) 
        {
            string keyBanner = primeKey + "Index:Noticias:TNoticias:text=" + text + ":page=" + page + ":dtInicio=" + dataInicio + ":dtFim=" + dataFinal;

            Func<object, List<NoticiasViewModel>> funcao = t => RetornaNoticias(text, page, dataInicio, dataFinal);
            return RedisService.GetOrSetToRedis(keyBanner, funcao, 30);
        }
        private List<NoticiasViewModel> RetornaNoticias(string text,int page, string dataInicio = null, string dataFinal = null)
        {

            DateTime? dtInicio = null;
            DateTime? dtFim = null;

            if (!String.IsNullOrEmpty(dataInicio))
            {
                dtInicio = DateTime.Parse(dataInicio).AddHours(0).AddMinutes(0).AddSeconds(0);
            }
            if (!String.IsNullOrEmpty(dataFinal))
            {
                dtFim = DateTime.Parse(dataFinal).AddHours(23).AddMinutes(59).AddSeconds(59);
            }

            var n = db.Noticias.Where(x => x.liberado &&
                                            !x.excluido &&
                                            x.dataAtualizacao < DateTime.Now &&
                                            x.Editoriais.Any(e => e.chave == CHAVE_EDITAL) &&
                                            x.idColunista == null &&
                                            (
                                                (text == null || (
                                                                    (x.titulo != null && x.titulo.Contains(text.ToLower())) ||
                                                                    (x.chamada != null && x.chamada.Contains(text)) ||
                                                                    (x.subtitulo != null && x.subtitulo.Contains(text))
                                                                )) &&
                                                (dtInicio == null || x.dataCadastro >= dtInicio) &&
                                                (dtFim == null || x.dataCadastro <= dtFim)
                                            )
                                        )
                                        .Select(noticia => new NoticiasViewModel
                {
                    Chamada = noticia.chamada,
                    DataCadastro = noticia.dataCadastro,
                    Editoriais = noticia.Editoriais.Select(editorial => new EditorialNoticiaViewModel
                    {
                        Ativo = editorial.ativo,
                        Chave = editorial.chave,
                        Especial = editorial.especial,
                        Esporte = editorial.esportes,
                        Excluido = editorial.excluido,
                        Nome = editorial.nome

                    }).Take(1),
                    Foto = noticia.foto,
                    Id = noticia.id,
                    PorAutor = noticia.porAutor,
                    TipoDestaque = noticia.TipoDestaque,
                    Titulo = noticia.titulo,
                    TituloCapa = noticia.TituloCapa,
                    Url = noticia.url,
                    Audio = noticia.audio,
                    Liberado = noticia.liberado,
                    Excluido = noticia.excluido,
                    IdColunista = noticia.idColunista,
                    Plantao = noticia.plantao
                }).OrderByDescending(y => y.DataCadastro).Take(200).AsNoTracking().ToList();
            
            return n;
        }

        private List<BannerSeuBolsoViewModel> BannersCached()
        {
            string keyBanner = primeKey + "Index:Banners:TBanners";

            Func<object, List<BannerSeuBolsoViewModel>> funcao = t => BannersSeuBolsoDB();
            return RedisService.GetOrSetToRedis(keyBanner, funcao, 600);
        }

        private List<BannerSeuBolsoViewModel> BannersSeuBolsoDB()
        {
            // esta pegando todos os banners como a home, fazer filtro futuramente
            // também fazer na home

            var hoje = DateTime.Now;
            var bannersGeneral = db.Banners.Where(x => x.Liberado && !x.Excluido && hoje >= x.DataInicio && hoje <= x.DataFim)
                .Select(banner => new BannerSeuBolsoViewModel
                {
                    Arquivos = banner.Arquivo,
                    Id = banner.Id,
                    Link = banner.Link,
                    Titulo = banner.Titulo,
                    Chave = banner.AreaBanner.FirstOrDefault().chave,
                    Anunciante = banner.Anunciante,
                    AreaBannerDescricao = banner.AreaBanner.FirstOrDefault().Descricao,
                    AreaBannerTamanho = banner.AreaBanner.FirstOrDefault().Tamanho,
                    AreaBannerAtivo = banner.AreaBanner.FirstOrDefault().Ativo.Value
                }).ToList();
            return bannersGeneral;
        }
    }
}

Site/Views/SeuBolso/Index.cshtml
@model Site.ViewModels.SeuBolso.SeuBolsoViewModel
@using System.Text.RegularExpressions
@using PagedList.Mvc
@using Site.Helpers;    
@{
    ViewBag.Title = "Index";

    var bannerlateral = Model.Banners.Where(x => x.Chave == "seu-bolso1").OrderBy(x => Guid.NewGuid()).FirstOrDefault();
    var bannercentral = Model.Banners.Where(x => x.Chave == "seu-bolso").OrderBy(x => Guid.NewGuid()).FirstOrDefault();
    var bannerrodape = Model.Banners.Where(x => x.Chave == "seu-bolso2").OrderBy(x => Guid.NewGuid()).FirstOrDefault();
    
}
@section SEO{
    <meta name="DC.title" content="Banco Inter - Rádio CompanyName | A Rádio de Minas" />
    <meta property="og:title" content="Banco Inter - Rádio CompanyName | A Rádio de Minas" />
    <meta property="og:type" content="website" />
    <meta property="og:description" content="" />
    <meta property="og:image" content="@Url.Content("~/images/ico-facebook.jpg")" />
    <meta property="og:url" content="@HttpContext.Current.Request.Url.AbsoluteUri" />
    <title>Banco Inter - Rádio CompanyName | A Rádio de Minas</title>
}
@section css{
    <link rel="apple-touch-icon" href="apple-touch-icon.png">
    @Styles.Render("~/Content/seubolso")
} 

<div class="wrapper-general center" style="padding-top: 245px;">
    <h1 class="title-page" style="margin-top: 20px;">Seu Bolso - Banco Inter</h1>
    <header class="nav-intern clearfix">
        <div class="buttons">
            <a class="bt-back" href="javascript:window.history.go(-1)"> <i class="fa fa-angle-left"></i> Voltar</a>
            Texto: <button class="more bt-resize">+</button> <button class="bt-resize minus">-</button>
        </div>
        <nav class="breadcumb">
            <a href="@Url.Action("Index","Home")">Home</a>
            <a href="#">Especiais</a>
            <a href="#">Seu Bolso</a>
            <span>Banco Inter</span>
        </nav>
    </header>
</div>
    <div class="content-bancointer">

        <div class="banner-bi" style="margin-bottom: 40px;">
            <div class="list-ban">
                <div class="item" style="background-image: url('images/ban-bancointer1.jpg')">
                    <div class="center">
                        <div class="info">
                            <p class="title">JUNTAR QUASE R$7.000,00 EM 52 SEMANAS É POSSÍVEL!</p>
                            <p>Estudos, viagens, trocar de carro, redecorar a casa... Início de ano é cheio de planos. Dizem que “sonhar não custa nada”, ...</p>
                            <a href="https://bancointer.com.br/" target="_blank">
                                <button>SAIBA COMO, aqui</button>
                            </a>
                        </div>

                    </div>
                </div>
            </div>

        </div>

        <div class="center">
            <div class="row-grid clearfix">
                <div class="grid-6">
                    <div class="box-bi hm290">
                        <div class="grid-7">
                            <p class="tit">Seu Bolso</p>
                            <p>Como você anda cuidando das suas finanças pessoais? Qual é o sua situação financeira?</p>
                            <p>Veja em que situação você se encontra!</p>
                        </div>
                        <div class="grid-5 align-center">
                            <img src="../images/ico-calc.png" alt="">
                            <a onclick="abrefuncy('.float-seubolso');">
                                <button>
                                    Calcular agora
                                </button>
                            </a>
                        </div>

                    </div>
                </div>
                <div class="grid-6">
                    @if (Model.Indicadores.Bovespa != null)
                    {
                        <div class="box-bi hm290">
                            <div class="grid-4">
                                <p class="tit">ibovespa</p>
                                <div class="border"></div>
                                <p class="txt-porc">
                                    @Model.Indicadores.Bovespa.PercentualVariacao
                                    <small>
                                        %
                                    </small>
                                </p>
                                <p class="txt-pont">@Model.Indicadores.Bovespa.Pontos</p>
                            </div>
                            <div class="grid-8">
                                <div class="txt border clearfix">
                                    <p class="tit">moeda</p>
                                    <p class="ibo-com">compra</p>
                                </div>
                                <div class="txt border clearfix">
                                    <p>Dólar</p>
                                    <p id="dolarvalor">R$ 3,576</p>
                                </div>
                                <div class="txt border clearfix">
                                    <p>Euro</p>
                                    <p id="eurovalor">R$ 3,975</p>
                                </div>
                                <div class="txt clearfix">
                                    <p>libra</p>
                                    <p id="libravalor">R$ 0,211</p>
                                </div>
                            </div>
                            <div class="border clearfix"></div>
                            <p class="legenda clearfix">Atualizado: 10/10/2016, 10h19</p>
                        </div>
                    }
                </div>
            </div>
            <div class="row-grid clearfix">
                <div class="grid-9">
                    <div class="grid-4">
                        <div class="box-bi hm320">
                            <p class="tit">Conversor de moedas</p>
                            <div class="bi-conversordemoedas">
                                <fieldset>
                                    <label for="conversor-de">de</label>
                                    <select name="conversor-de" id="conversor-de">
                                        <option value="BRL">R$ - Real</option>
                                        <option value="USD">$ - Dolar</option>
                                        <option value="GBP">£ - Libra</option>
                                        <option value="EUR">€ - Euro</option>
                                    </select>
                                </fieldset>
                                <fieldset>
                                    <label for="conversor-para">para</label>
                                    <select name="conversor-para" id="conversor-para">
                                        <option value="USD">$ - Dolar</option>
                                        <option value="GBP">£ - Libra</option>
                                        <option value="EUR">€ - Euro</option>
                                        <option value="BRL">R$ - Real</option>
                                    </select>
                                </fieldset>
                                <fieldset>
                                    <label for="conversor-valor">valor</label>
                                    <input type="text" value="0,00" name="conversor-valor" id="conversor-valor">
                                </fieldset>
                                <p>Resultado <strong id="conversor-resultado">0,00</strong></p>
                            </div>
                        </div>
                    </div>
                    <div class="grid-4">
                        <div class="box-bi hm320">
                            <p class="tit">Commodities</p>
                            <div class="commodities-base" style="height: 20px;width: 100%;background: #f6f6f6;position: absolute;"></div>
                            <iframe frameborder="0" scrolling="no" height="230" width="100%" allowtransparency="true" marginwidth="0" marginheight="0" src="https://sslcomrates.forexprostools.com/index.php?force_lang=12&pairs_ids=8851;49768;13916;959199;8869;8914;8894;959207;8830;8836;&header-text-color=%23FFFFFF&header-bg=%23ad1111&curr-name-color=%230059b0&inner-text-color=%23000000&green-text-color=%232A8215&green-background=%23B7F4C2&red-text-color=%23DC0001&red-background=%23FFE2E2&inner-border-color=%23ffffff&border-color=%23ffffff&bg1=%23F6F6F6&bg2=%23ffffff&last=hide&open=hide&month=hide&high=hide&low=hide&change=hide&last_update=hide"></iframe>
                        </div>
                    </div>
                    <div class="grid-4">
                        <div class="box-bi hm320">
                            <p class="tit">Indicadores</p>
                            <div class="bi-indicadores">

                                @foreach (var i in Model.Indicadores.Financeiros)
                                {
                                    @Html.Raw(String.Format("<p>{0}<span>{1}</span></p>", i.Nome, i.Valor));
                                }

                            </div>
                        </div>
                    </div>

                </div>

                <aside class="grid-3 wrap-aponse">

                    @if (bannerlateral != null)
                    {
                        <a href="@(!string.IsNullOrEmpty(bannerlateral.Link)? bannerlateral.Link:" #")" target="_blank" onclick="clickBanner(@bannerlateral.Id)">
                            <img style="margin-bottom: 40px; margin-top:0" class="random-banner promotional-banner"
                                 data-cliente="@bannerlateral.Anunciante"
                                 data-comercial="@bannerlateral.AreaBannerDescricao"
                                 data-dimensao="@bannerlateral.AreaBannerTamanho"
                                 data-banner-id="@bannerlateral.Id"
                                 src="/admin/Conteudo/Banners/@bannerlateral.AreaBannerTamanho/@bannerlateral.Arquivos"
                                 alt="@bannerlateral.Titulo">
                        </a>
                    }
                </aside>

                <div class="grid-12">
                    @if (bannercentral != null)
                        {
                            <a href="@(!string.IsNullOrEmpty(bannercentral.Link)? bannercentral.Link:" #")" target="_blank" onclick="clickBanner(@bannercentral.Id)">
                                <img style="margin: 0" class="random-banner promotional-banner"
                                    data-cliente="@bannercentral.Anunciante"
                                    data-comercial="@bannercentral.AreaBannerDescricao"
                                    data-dimensao="@bannercentral.AreaBannerTamanho"
                                    data-banner-id="@bannercentral.Id"
                                    src="/admin/Conteudo/Banners/@bannercentral.AreaBannerTamanho/@bannercentral.Arquivos"
                                    alt="@bannercentral.Titulo">

                            </a>
                        }
                </div>
                <div class="grid-9">
                    @Html.Partial("_NoticiasSeuBolso",Model)
                </div>
                <aside class="grid-3 wrap-aponse">
                    @Html.Partial("_Aposentadoria")
                 </aside>

                @if (bannerrodape != null) {
                    <a href="@(!string.IsNullOrEmpty(bannerrodape.Link)? bannerrodape.Link:" #")" target="_blank" onclick="clickBanner(@bannerrodape.Id)">
                        <img style="margin-top: 0" class="random-banner promotional-banner"
                             data-cliente="@bannerrodape.Anunciante"
                             data-comercial="@bannerrodape.AreaBannerDescricao"
                             data-dimensao="@bannerrodape.AreaBannerTamanho"
                             data-banner-id="@bannerrodape.Id"
                             src="/admin/Conteudo/Banners/@bannerrodape.AreaBannerTamanho/@bannerrodape.Arquivos"
                             alt="@bannerrodape.Titulo">
                    </a>
                }
            </div>
        </div>

    </div>

    @Html.Partial("_SeuBolso")


    <div class="float-aposentado" id="float-aposentado" style="display: none;">
        <div class="content-fl-apo">
            <p class="subtit">Você vai se aposentar com</p>
            <p id="paragrafoaposentadoria" class="title">60 anos</p>
            <p>A simulação não possui efeito legal nem garante o direito ao benefício, se as condições informadas ao realizar o cálculo não forem comprovadas quando você solicitar o benefício ao INSS.</p>
        </div>
    </div>

    @section script_seubolso{
        @Scripts.Render("~/bundles/seubolso");
    }

Site/Views/SeuBolso/_Aposentadoria.cshtml
<div class="box-bi">
    <p class="tit">aposentadoria </p>
    <p>Veja quando você vai se aposentar com a nova regra</p>
    <form id="formcalcular">
        <div class="apon-sexo">
            <label for="man" class="labelsexo ativo">
                <input type="radio" name="sexo" value="m" id="man" checked="checked">
                Homem
            </label>
            <label for="wom" class="labelsexo">
                <input type="radio" name="sexo" value="f" id="wom">
                Mulher
            </label>
        </div>
        <fieldset>
            <label for="apon-serv">Servidor(a)</label>
            <select name="" id="apon-serv" required>
                <option value="">Selecione</option>
                <option value="1">Publico</option>
                <option value="2">Privado</option>
            </select>
        </fieldset>
        <fieldset>
            <label for="apon-ida">Sua idade atual</label>
            <input type="text" id="apon-ida" placeholder="Digite aqui" required>
        </fieldset>
        <fieldset>
            <label for="apon-inss">Anos que já contribuiu INSS</label>
            <input type="text" id="apon-inss" placeholder="Exemplo: 25" required>
        </fieldset>
        <input id="calcularaposentadoria" type="submit" value="calcular" data-fancybox data-src="#float-aposentado" data-options='{"smallBtn" : false}'>
    </form>
</div>

Site/Views/SeuBolso/_NoticiasSeuBolso.cshtml
@model Site.ViewModels.SeuBolso.SeuBolsoViewModel
@using System.Text.RegularExpressions
@using PagedList.Mvc
@using Site.Helpers;
  
<section>
    <header class="filters">

        @using (Html.BeginForm("Index", "SeuBolso", FormMethod.Get, new { @class = "row-grid clearfix" })) {
            <div class="grid-7">
                <label for="palavrachave">Palavra Chave</label>
                <input type="text" class="input-form" name="palavraChave" id="palavraChave" value="@Request.Params["palavrachave"]">
            </div>

                                @*<div class="grid-2">
                                        <label for="categoria">Categoria</label>
                                        @Html.DropDownList("categoria", null, "Selecione...", new { @class = "input-form", @id = "categoria", @name = "categoria" })
                                    </div>*@
                                <div class="grid-2">
                                    <label for="datainicio">De</label>
                                    <input type="date" class="input-form dates" id="datainicio" value="@Request.Params["dataInicio"]" name="dataInicio">
                                </div>
                                <div class="grid-2">
                                    <label for="datafinal">Até</label>
                                    <input type="date" class="input-form dates" id="datafinal" value="@Request.Params["dataFinal"]" name="dataFinal">
                                </div>
                                <div class="grid-1">
                                    <button type="submit" id="post-search" title="Buscar" class="search-filter fa fa-search"></button>
                                </div>
        }

    </header>

    @if (Model.Noticias != null && Model.Noticias.Count > 0) {
        <ul class="news-line">
            @foreach (var item in Model.Noticias.ToList()) {
                var urlCompartilha = HttpContext.Current.Request.Url.Authority + Url.Action("Detalhes", "Noticias", new { chave = item.Url });
                <li>
                    <article class="container">

                        @if (!string.IsNullOrEmpty(item.Foto)) {
                            <figure>
                                <a href="@Url.Action("Detalhes", "Noticias", new { chave = item.Url })">
                                    <img src="@Utils.fullUrlImage("365x240", item.Id,365)" title="@Html.Raw(item.FotoCredito)" alt="@Html.Raw(item.FotoCredito)">
                                </a>
                            </figure>

                        }

                        <div class="info">
                            <div class="clearfix header-content">

                                <span class="info-publication">
                                    Por <strong>@item.PorAutor</strong>, @item.DataCadastro.ToShortDateString()  às  @item.DataCadastro.ToShortTimeString()
                                </span>

                                <div class="box-share">
                                    <span class="title">
                                        <i class="fa fa-share-alt"></i>Compartilhar
                                    </span>
                                    <nav>
                                        <a href="#" class="icon-facebook" onclick="openwindow('https://www.facebook.com/sharer/sharer.php?u=@urlCompartilha&display=popup&ref=plugin');">
                                            <i class="fa fa-facebook"></i> Facebook
                                        </a>

                                        <a href="#" class="icon-twitter-squared" onclick="openwindow('https://twitter.com/intent/tweet?text=@Regex.Replace(item.Chamada, @"<[^>]+>|&nbsp;", "").Trim()&url=@urlCompartilha');">
                                            <i class="fa fa-twitter"></i>Twitter
                                        </a>
                                    </nav>
                                </div>
                            </div>
                            <a href="@Url.Action("Detalhes", "Noticias", new { chave = item.Url })">
                                <span class="tag-area">@item.Titulo</span>
                                <h3 class="title-medium">@Html.Raw(item.Chamada)</h3>
                            </a>
                        </div>
                    </article>
                </li>
            }

        </ul>

                            <footer class="pagination-bottom">

                                <ul class="pag">
                                    @if (Model.Noticias.PageCount > 1) {
                                        @Html.PagedListPager(Model.Noticias, page => Url.Action("Index", new {
                                       page,
                                       palavrachave = Request.Params["palavrachave"],
                                       categoria = Request.Params["categoria"],
                                       datainicio = Request.Params["datainicio"],
                                       datafinal = Request.Params["datafinal"]
                                   }),
                           new PagedListRenderOptions {
                               LinkToNextPageFormat = "Próximo",
                               LinkToPreviousPageFormat = "Anterior",
                               MaximumPageNumbersToDisplay = 5,
                               DisplayLinkToLastPage = PagedListDisplayMode.Never,
                               DisplayLinkToFirstPage = PagedListDisplayMode.Never

                           })
                                    }
                                </ul>

                            </footer>
    } else {
        <div class="block-text">
            <h3>Não foram encontrados resultados.</h3>
        </div>
    }

</section>